- hosts: all
  become: yes
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  tasks:
    - copy:
        src: torb
        dest: /home/isucon/torb/webapp/go/torb
        owner: isucon
        group: isucon
        mode: 0775

    - copy:
        src: db/init.sh
        dest: /home/isucon/torb/db/init.sh
        owner: isucon
        group: isucon
        mode: 0755

    - copy:
        src: db/init-user.sh
        dest: /home/isucon/torb/db/init-user.sh
        owner: isucon
        group: isucon
        mode: 0755

    - copy:
        src: db/schema.sql
        dest: /home/isucon/torb/db/schema.sql
        owner: isucon
        group: isucon
        mode: 0644

    - systemd:
        name: torb.go.service
        state: restarted

    - command: curl localhost:8080/initialize
