- hosts: all
  become: yes
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  tasks:
    - copy:
        src: torb
        dest: /home/isucon/torb/webapp/go/torb
        owner: isucon
        group: isucon
        mode: 0775

    - systemd:
        name: torb.go.service
        state: restarted
